commit
Greyless/Neural-Style-Transfer pull request #13
Opened 2022-09-22 18:11 UTC by Greyless

Notes and assignments

2022-09-23 06:55 UTC, Neel-Shah-29 commented
@Greyless this is not the way to write the PR Title. Please provide the correct name to PR by editing the title.
Also your commit message is very vague if i merge this commit to master everyone can see this commit message which is not good, so please write a meaningful commit message and push the commit. Note that this previous commit should not be left! See the concept of reseting the head and how to force push!

2022-09-23 07:01 UTC, Neel-Shah-29 commented
1) Change the naming convention of Course 3 to Course 4 since we have not done course 3 its course 4 on coursera.
2) I am not looking at the technical details of each assignment i assume you have checked it from expected output.

2022-09-23 17:55 UTC, Neel-Shah-29 approved these changes
LGTM!
If nothing yet to be added we can merge the PR.

2022-09-24 12:08 UTC, shahpratham requested changes
@Greyless added few comments, otherwise LGTM.

2022-09-24 12:08 UTC, shahpratham commented on Deep Learning/Course_1_Lakshaya.md
> +![Performance vs Data](/Deep%20Learning/assets/Data%20vs%20Performance.png"Performance vs Data")
Image is not rendered here

2022-09-24 12:08 UTC, shahpratham commented on Deep Learning/Course_1_Lakshaya.md
> +![Sigmoid Function](/Deep%20Learning/assets/Sigmoid%20function.png"Sigmoid Function")
here as well

2022-09-24 12:08 UTC, shahpratham commented on Deep Learning/assets/Course_1_Lakshaya.md
> +# Neural Networks
remove this from assets

2022-09-24 13:45 UTC, shahpratham approved these changes

2022-09-24 13:46 UTC, merged